language: android
android: 
 components: 
    - build-tools-19.1.0 
    - build-tools-21.1.1
	- android-19
    - extra-google-google_play_services 
    - extra-google-m2repository 
    - extra-android-m2repository 
    - addon-google_apis-google-19 

 licenses: 
    - 'android-sdk-preview-license-52d11cd2' 
    - 'android-sdk-license-.+' 
    - 'google-gdk-license-.+' 
    - /android-sdk-license-[0-9a-f]{8}/ 

script: ./gradlew build 

before_install: 
    - chmod +x gradlew 
   
notifications: 
  slack: smart-navi-watch:aEOpYaZVURMj1eESnCcWBLHe